### PR TITLE
Removed comment from the third line of the shadowJar contents

### PR DESCRIPTION
**Pull request by ahinchman1**
Target branch is pointed to `rr-meta-prototype-integration`
#1690

### CODE REVIEW

**Comment by pakoito** [comment]
```
> Task :arrow-annotations:ktlintMainSourceSetCheck
/home/travis/build/arrow-kt/arrow/modules/meta/arrow-annotations/src/main/java/arrow/higherkind.kt:3:1: Missing space after //
"plain" report written to /home/travis/build/arrow-kt/arrow/modules/meta/arrow-annotations/build/reports/ktlint/ktlintMainSourceSetCheck.txt
```

_squint_ how did this reach prod?

**Comment by ahinchman1** [comment]
I could be wrong, but we were wrangling with this particular task yesterday, but @rachelcarmena made a PR yesterday to give us the ability to build the jar of the project - but I think this is still an issue otherwise.

**Comment by pakoito** [comment]
Oh, merge at will then.

**Comment by JorgeCastilloPrz** [comment]
What'd be the purpose of the line?

**Comment by rachelcarmena** [comment]
> What'd be the purpose of the line and why uncommenting? Could we provide more details in the PR description?

It was commented to make a local check and then it was pushed the change by mistake.

Merging on `rr-meta-prototype` branch!

**Comment by rachelcarmena** [comment]
`publishAndRunIde` continues working OK after merging :+1:

**Pull request merged**
