### PR TITLE
Enable project parallelism for Gradle

### PR DESCRIPTION
**Pull request by mkobit**
-----

I saw a pretty significant speed up locally from this, time to see see if it applies to CI as well.

### CODE REVIEW

**Comment by pakoito** [comment]
Does this affect tests? We have to avoid parallelism in tests.

**Comment by pakoito** [comment]
See #1137

**Comment by mkobit** [comment]
It should not impact tests in each individual project. If the tests in an individual project run one-at-time (or whatever order they do today), then it will continue to do that. This change should make independent projects build in parallel, so hopefully get multiple test tasks of those projects running at the same time. However, surprisingly to me, the build at https://travis-ci.org/arrow-kt/arrow/builds/536896884 was `29 min 13 sec` which doesn't seem much faster than I would have expected.

I did actually see that issue in `IOTest` earlier before this change, so I'll also follow up on https://github.com/arrow-kt/arrow/issues/1137.

**Comment by aballano** [comment]
It seems that it decreased the CI check from 33-34min to 31 (~8.8%) 👍 Let me re-run the check some more times to check that there's no flakiness due to the changes and also to measure the time a bit more 👌

**Comment by pakoito** [comment]
https://travis-ci.org/arrow-kt/arrow/jobs/536896885#L2946-L2947

**Comment by nomisRev** [comment]
@pakoito given that it's green and I could not reproduce locally should we merge?

**Comment by pakoito** [comment]
go for it

**Pull request merged**
