### PR TITLE
Java9support

### PR DESCRIPTION
**Pull request by Cottand**
Moved typealiases outside of package io.kidedj in order to not declare that package twice. I now realise I didn't need to create a new PR, sorry about that!

### CODE REVIEW

**Comment by Cottand** [comment]
See #1196

**Comment by Cottand** [comment]
I'll fix it

**Comment by pakoito** [comment]
https://travis-ci.org/arrow-kt/arrow/jobs/570584156#L604

**Comment by Cottand** [comment]
Yes I saw, but I can't even build the untouched master branch locally. I am clearly missing some dependency but I can't seem to find info on how to build arrow

**Comment by Cottand** [comment]
Either that or it's just me being a noob really

**Comment by pakoito** [comment]
It seems like there are other instances of HkJ2 that need their import updated, such as `AndThen.kt`.

I'd suggest using IntelliJ's refactor rather than just text replacement.

**Comment by Cottand** [comment]
I did use IntelliJ's refactor, it's kind of why I'm surprised, it really is the simplest thing to do. But again, it can't even build master so that's why refactoring must have gone wrong. I'll figure out why my configuration is wrong, do the refactor, make sure I pass tests and then I'll merge that here.

**Comment by Cottand** [comment]
Hi Paco, the build is passing now

**Comment by pakoito** [comment]
The commit is showing as +0, -0. I believe you smashed all changes.

**Comment by pakoito** [comment]
It's very close now! https://travis-ci.org/arrow-kt/arrow/jobs/573113865#L3602

**Comment by Cottand** [comment]
You're right, sorry for wasting your time. I fixed the missing import now (turns out I needed to change the import in your generated source files too). That build fail has to do with the docs? (I haven't touched anything in that module) It compiled on my end, I am guessing it has to do with one of the merges that happened in the last days. I will keep investigating :)

**Comment by pakoito** [comment]
You aren't wasting my time, don't worry. I'm cheering for this :D

**Comment by Cottand** [comment]
Hahah thanks. I am just very unfamiliar with things like code generation through annotation processing. Turns out it had nothing to do with recent PRs too, it was a typo on my end

**Comment by pakoito** [comment]
And we're merging it! Thanks @Cottand

**Comment by Cottand** [comment]
Hahah yes cheers

**Comment by Cottand** [comment]
Anything else that needs to be done in order to close #1196 though?

**Comment by pakoito** [comment]
I really don't know. Try posting in the issue and ask the original author!!

**Comment by Cottand** [comment]
Good point thanks

**Pull request merged**
