### PR TITLE
Show constructor to use receiver type to enable object property access

### PR DESCRIPTION
**Pull request by ersin-ertan**
Solves: https://github.com/arrow-kt/arrow/issues/830

### CODE REVIEW

**Comment by pakoito** [comment]
Could you please use this chance to add a reference to the `invoke` constructor in the docs? I'm surprised we don't use it in the codebase either, so good news hahaha

**Comment by ersin-ertan** [comment]
Good tip - I'll create a snippet

**Comment by pakoito** [comment]
This is a great chance to learn about Ank!! Ank is the tool we use to compile snippets. What is does is output the result of the last expression inside a block. With the changes you've introduced, as they're in the same block, they won't produce the snippet result. Compare the docs with the source: https://arrow-kt.io/docs/typeclasses/show/

If you'd like to test Ank, use `./gradlew runAnk`, and find the files in the arrow-docs output folder.

**Comment by ersin-ertan** [comment]
Show and Eq examples moved to Create your own instance locations.
Previous commits squashed into a single commit.
Updated branch with other arrow commits. 
:+1:

**Comment by pakoito** [comment]
Thanks @ersin-ertan for the contribution!

**Pull request merged**
