### PR TITLE
Inline functions with lambda parameters and remove crossinline modifiers

### PR DESCRIPTION
**Pull request by kevinherron**
This makes the affected functions usable when the function parameter is
a suspending function and the Try data structure generally more usable
in a project using coroutines.

### CODE REVIEW

**Comment by kevinherron** [comment]
If the changes look okay, I figure we can proceed two ways:

1. one PR per data structure
2. this PR can become the landing pad for "coroutine-friendly" changes to all desired data structures

**Comment by raulraja** [comment]
@kevinherron since these changes introduce multiple binary incompatible changes I'd be inclined to do it all in one big PR, merge and release a new major version. All users that have created custom instances will have to regenerate and fix compilation errors since this will change the function signature when this gets applied to the `arrow-typeclasses` and `arrow-instances` modules and other libs in arrow like `arrow-optics` which also provide instances. If you agree with this plan we can continue in this same PR.

**Comment by kevinherron** [comment]
TODO (incomplete list)
- [x] Try
- [ ] Either
- [ ] Option
- [ ] Validated
- [ ] NonEmptyList
- [ ] Ior
- [ ] State

**Comment by kevinherron** [comment]
I haven't forgotten about this, just been at conferences and on-site with customers and otherwise just not at my desk able to do programming for the last 2 weeks 😭

**Comment by pakoito** [comment]
@kevinherron We am so disappointed in you Kevin. The fact that you've put important meetings and conferences before opensource work that you do for free and for fun is just shameful /s

Don't worry Kevin, I'm personally excited for this change to be merged to improve comprehensions, take all the time you need!

**Comment by kevinherron** [comment]
I'm unlikely to ever finish this PR, and for all I know current versions have already fixed this. Closing to keep things tidy ✅

**Comment by pakoito** [comment]
@kevinherron I did a pass on the datatypes in core to make them more consistent. Thanks for noticing :D Hope you're liking 0.7.3

**Pull request closed without merging**
