### PR TITLE
Fix potential classloader deadlock in Either, Validated, Option, Ior, and Eval (#2375)

### PR DESCRIPTION
**Pull request by dberg**

### CODE REVIEW

**Comment by nomisRev** [comment]
Looks great @dberg! 👏 
We need to do the same for `Eval.kt`, `Ior.kt`, `Option.kt`, and then I think this is good to go 👍

**Comment by dberg** [comment]
@nomisRev, I've applied the changes to Eval, Ior, and Option as well. They should all follow the same pattern now. I was also able to reproduce the deadlock prior to the changes in all classes on my local machine.

**Comment by rachelcarmena** [comment]
Welcome to Arrow @dberg !! :raised_hands:

**Review by nomisRev — APPROVED** [review]
Looks perfect @dberg!! Thank you for your contribution, and congrats on your first contribution in Arrow 🥳 Welcome to the Arrow 😁

**Review by danimontoya — APPROVED** [review]
Awesome! thanks @dberg for your contribution 🙌 🚀

**Pull request merged**
