### PR TITLE
[WIP] - Community Resources

### PR DESCRIPTION
**Pull request by israelperezglez**
@calvellido could you review this PR please?

### CODE REVIEW

**Comment by pakoito** [comment]
> +24,451 −336

**Comment by JorgeCastilloPrz** [comment]
Easy to review!

**Comment by raulraja** [comment]
Looks like there is an error with this branch, it contains pretty much the entire of arrow nested under _site

**Comment by calvellido** [comment]
Ok, I tried my best to bring this back to life, @israelperezglez could you please continue working from now on, or check that everything is ok if it was considered done?

From my point of view I feel a bit weird the difference in the /blogs/ section and the actual? blog section (the one that appears when you click on a category).

**Comment by calvellido** [comment]
Superseded by a new PR #1260

**Pull request closed without merging**
