### PR TITLE
Moved hkjs.kt to package arrow in order to enable java9+ support

### PR DESCRIPTION
**Pull request by Cottand**
Moved hkjs.kt out of io.kindedj in order to not declare io.kindedj in more than one jar, see #1196

### CODE REVIEW

**Comment by pakoito** [comment]
Please check what's failing on the travis build so we can fix it before approving this PR :D

Thanks for your effort!

**Comment by Cottand** [comment]
Oh sorry about that

**Comment by pakoito** [comment]
????

**Comment by pakoito** [comment]
There was no need to delete it, the build was failing, it just needed some fix! :D

**Pull request closed without merging**
