### PR TITLE
Updated Maven section for 0.9.0

### PR DESCRIPTION
**Pull request by routis**
Updated the section of the Maven Basic setup to use the -new- jars released under 0.9.0 tag

### CODE REVIEW

**Comment by routis** [comment]
@pakoito Can you please merge this?

**Comment by pakoito** [comment]
Yep! Done :D

**Comment by routis** [comment]
@pakoito Unfortunately, current doc page (https://arrow-kt.io/docs/) displays again the old version.

**Comment by calvellido** [comment]
Yeah, sorry about that. Basically, if this was merged after 0.9.0 was released, we will need to add it manually to those docs, as the current page is the frozen docs state of the stable release.

Live docs resides now here: https://next.arrow-kt.io/

**Pull request merged**
