### PR TITLE
WIP: arrow-examples

### PR DESCRIPTION
**Pull request by jmfayard**
(Work in progress pull-request)

Trying to continue working on the examples. Hope that helps

Application and Functor come first

### CODE REVIEW

**Comment by pakoito** [comment]
One suggestion: link from the docs to each individual file!

**Comment by raulraja** [comment]
@jmfayard thanks so much, these are very helpful and useful. It will become the base of our version of https://try.kotlinlang.org/ that we plan on hosting at `try.arrow-kt.io`. If you want to collaborate with me and @Guardiola31337 we have a fork ready at: https://github.com/arrow-kt/try.arrow-kt.io

The content you are creating is better suited there as those will become executable online for others to try out without having to add arrow as a dependency to try it.

**Comment by jmfayard** [comment]
@raulraja This is awesome, I was exactly wondering wether making them executable could be possible!

Can this container runs tests?

**Comment by raulraja** [comment]
@jmfayard I believe so, @Guardiola31337 is woring on making the fork run, once he gets it to run he will post easier instructions on how to run it. If you want to help feel free to reach out in kotlin slack #arrow-contributors and we can see what we can do with it.

**Comment by jmfayard** [comment]
I gave up on this, I am sorry. Should this be closed?

**Pull request closed without merging**
