### PR TITLE
Update README.md with the core/data split

### PR DESCRIPTION
**Pull request by wiyarmir**
Just noticed it setting up a new project.

### CODE REVIEW

**Comment by pakoito** [comment]
Data is no more. Raul has more context.

**Comment by pakoito** [comment]
Also what are you setting up, ladrón :*

**Comment by raulraja** [comment]
sorry, this has not been released yet, therefore the confusion, but in 0.9.0 all those changes in the README are taken into consideration. We will support multi-version docs after 1.0

**Comment by wiyarmir** [comment]
😄 that serves me well for being disconnected

**Pull request closed without merging**
