### PR TITLE
Merge master into release/0.13.0

### PR DESCRIPTION
**Pull request by nomisRev**

### CODE REVIEW

**Review by rachelcarmena — APPROVED** [review]
:rocket:

**Comment by rachelcarmena** [comment]
@nomisRev , select `Create a merge commit` when merging this PR

**Comment by rachelcarmena** [comment]
@nomisRev , select `Rebase and merge` when merging this PR

**Comment by rachelcarmena** [comment]
> @nomisRev , select `Rebase and merge` when merging this PR

Sorry, I missed `please` :woman_facepalming:

**Review by i-walker — APPROVED** [review]
Thanks @nomisRev 🙌

**Comment by rachelcarmena** [comment]
Recovering the branch to redo the PR with "rebase and merge"

**Comment by rachelcarmena** [comment]
Fixed into the branch directly removing/adding the protection again because all the checks passed with this branch.

**Comment by i-walker** [comment]
Sorry folks 😭

**Comment by rachelcarmena** [comment]
Don't worry @i-walker :raised_hands: Easy to solve!! Nothing to apologize!! :green_heart:

**Pull request merged**
