### PR TITLE
Increase currying test coverage (#2894)

### PR DESCRIPTION
**Pull request by lgtout**
This PR achieves 100% test coverage for `curried`, `uncurried`, `curriedEffect`, and `uncurriedEffect`.

Arity-22 `uncurriedEffect` was missing, so I added it and updated `arrow-core.api`.

Currently Kotest's `checkAll`, `forAll`, `forNone` do not support tests with more than 12 generators.  

As such, I had to submit a [PR](https://github.com/kotest/kotest/issues/3382) to Kotest to support up to 22 generators in order to use property testing on Arrow's curry functions.  

The Kotest PR has been merged into `master` and is due to ship in the next release (`5.6.0`).  But it's unclear [when](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1676745188392509) that will be.  

I was able to use the Kotest update by adding the snapshot repository address
`https://s01.oss.sonatype.org/content/repositories/snapshots/` and setting Kotest version to `5.6.0.1188-SNAPSHOT`.  But I didn't include those build changes in this PR.

As such, this PR will fail the Arrow pipeline.  Other than that, the PR is complete.

Related: closed draft [PR](https://github.com/arrow-kt/arrow/pull/2917) to get feedback on general direction of changes.

### CODE REVIEW

**Comment by serras** [comment]
@lgtout would it be possible to comment out the code which doesn't work because of the required Kotest changes, so we can merge the one that works and then put the commented out one back when Kotest is updated?

**Comment by serras** [comment]
@lgtout I've move forward and commented out the tests myself. Is there something else you want in this PR, or could be mark it as ready for review?

**Comment by lgtout** [comment]
Thank you @serras .  No, nothing else.  Can be marked as ready-for-review.

**Review by serras — APPROVED** [review]

**Review by nomisRev — APPROVED** [review]

**Comment by nomisRev** [comment]
Thank you @lgtout! 🙌

**Pull request merged**
