### PR TITLE
Dm bump kotlin version

### PR DESCRIPTION
**Pull request by rachelcarmena**
Branch by @danimontoya (I'm repeating the PR to show the failures)

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Branch wasn't updated... running again...

**Comment by danimontoya** [comment]
Failed on fx, checking it out 👀

**Comment by danimontoya** [comment]
Its actually not possible to bump the version due to this
https://youtrack.jetbrains.com/issue/KT-35942
so closing the PR

**Comment by danimontoya** [comment]
Comment is within the same issue ticket: https://youtrack.jetbrains.com/issue/KT-35942

**Pull request merged**
