### PR TITLE
Code block style

### PR DESCRIPTION
**Pull request by israelperezglez**
@could you review this PR please? ;)

### CODE REVIEW

**Comment by israelperezglez** [comment]
Attached is a screenshot of what the code snippet would look like. I had to create a horizontal and vertical bar, because of the size of the code.
Captura de pantalla 2021-12-15 a las 17 15 50

**Review by raulraja — APPROVED** [review]
thanks @israelperezglez !

**Comment by nomisRev** [comment]
We can try improving these snippets by using Knit include imports, right?
Or snippet specific `<!--- INCLUDE -->` that way you can get rid of the unwanted imports, or any other snippet setup.

**Comment by nomisRev** [comment]
@israelperezglez @franciscodr I updated the snippets to look like the old ones using KotlinX Knit `INCLUDE` comments.

cc\\ @raulraja @JavierSegoviaCordoba I don't think KotlinX Knit is running on the code snippets in the arrow-site project.

**Comment by rafaparadela** [comment]
Task linked: [CU-1nq2vep Review CSS styles for code snippets on the landing page](https://app.clickup.com/t/1nq2vep)

**Review by franciscodr — APPROVED** [review]
Thanks @israelperezglez!

**Pull request merged**
