### PR TITLE
Rename files we've found using MD as extension instead of md

### LINKED ISSUE #1363: Docs with .MD extension (caps) fail to be edited
Repro: 

Go to https://arrow-kt.io/docs/optics/index/
Click Edit on the top right
BROKEN LINK
Edit url from `.md` to `.MD`
Fixed!

Fix:
Rename all `.MD` files to `.md`

https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/promise/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/filterindex/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/fiber/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/index/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/snoc/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/optics/cons/README.MD
https://github.com/arrow-kt/arrow/blob/master/modules/docs/arrow-docs/docs/docs/effects/ref/README.MD

### PR DESCRIPTION
**Pull request by pedrovgs**
### :pushpin: References
* **Issue:** Fixes #1363 

### :tophat: What is the goal?

Rename some files to be able to point to the correct GitHub URL from the documentation edit button.

### How is it being implemented?

To implement this PR we've run a small command to ensure the files @pakoito pointed out were the ones we needed to rename. This is the command: 

```
find . -type f -name "*.MD"
```

Then using ``git mv`` we've renamed these files 😃

### CODE REVIEW

**Comment by calvellido** [comment]
The side effect of this renaming is that it seems like previously those files with the all caps extensions weren't part of the ANK process?

It fails in 

`/modules/docs/arrow-docs/build/site/docs/effects/fiber/README.md`

```kotlin
import arrow.effects.*
import kotlinx.coroutines.Dispatchers.Default
import arrow.effects.extensions.io.fx.fx
import arrow.effects.typeclasses.Fiber
fun <A, B, C> parallelMap(first: IO<A>,
                     second: IO<B>,
                     f: (A, B) -> C): IO<C> =
  fx {
    val (fiberOne: Fiber<ForIO, A>) = Default.startfiber(first)
    val (fiberTwo: Fiber<ForIO, B>) = Default.startFiber(second)
    f(!fiberOne.join, !fiberTwo.join)
  }
val first = IO.sleep(5000).map {
  println("Hi, I am first")
  1
}
val second = IO.sleep(3000).map {
  println("Hi, I am second")
  2
}
```

with:

```kotlin
error: unresolved reference: startfiber
    val (fiberOne: Fiber<ForIO, A>) = Default.startfiber(first)
                                              ^
error: function invocation 'join()' expected
    f(!fiberOne.join, !fiberTwo.join)
                                ^
error: unresolved reference: sleep
val first = IO.sleep(5000).map {
               ^
error: unresolved reference: sleep
val second = IO.sleep(3000).map {
                ^
```

**Comment by pedrovgs** [comment]
@calvellido I was waiting for the build on Triavis/Bitrise because I've got the same error on my laptop but I thought it was something weird related to my repository. I'm going to take a look at those errors right now. Thanks for the info 😃 !

**Comment by calvellido** [comment]
Maybe @pakoito knew it all along and the `noob-friendly` tag...

IT'S A TRAP

**Comment by pedrovgs** [comment]
I've added some extra commits fixing some typos and replacing some functions that don't exist in this part of this documentation. Last but not least, @raulraja help me with the fix for parallelMap2 implementation. The issue was related to some missing imports 😃 Now the build should pass. Let's see what Travis and Circle CI say.

**Comment by pedrovgs** [comment]
build passing @calvellido \o/

**Comment by pakoito** [comment]
Oh, shit, nnnice :D Thanks @pedrovgs

**Comment by raulraja** [comment]
thanks @pedrovgs 🙋‍♂️

**Pull request merged**
