### PR TITLE
Adds docs for Category typeclass

### PR DESCRIPTION
**Pull request by paulcadman**
I'm not sure what to write as a brief description of Category. Should I add the definition into the docs?

So far I've opted to link to Bartosz Milewski's work.

### CODE REVIEW

**Comment by pakoito** [comment]
What would you use a category for? Better than focusing on the what it is, go for the what it can do!

**Comment by paulcadman** [comment]
@pakoito maybe I need some more instances in the library before I can show what it could be used for. I will try to add some.

**Comment by paulcadman** [comment]
I'm on holiday until the end of the month, so I won't be working on this until then.

**Comment by pakoito** [comment]
No hurries, I'm just happy you're contributing :D

**Comment by JorgeCastilloPrz** [comment]
In an effort to clean the PR list we've decided to close all the ones that are older than 2 months and consider them obsolete except for very specific circumstances that we will evaluate per PR. This PR has been in standby for too long so we're closing it. Note it can be brought back to life or browsed if at some point we need these docs.

**Pull request closed without merging**
