### PR TITLE
(WIP) OptionT video

### PR DESCRIPTION
**Pull request by israelperezglez**
@raulraja could you review this PR please?

### CODE REVIEW

**Comment by pakoito** [comment]
The slides with `map` are missing the Functor parameter. In the refactor we're doing, that functor will probably become the first parameter of the function.

**Comment by pakoito** [comment]
Worth noting that CI will keep on failing until that Ank dependency gets published on maven.

**Comment by Guardiola31337** [comment]
If you rebase from `master` docs should work again 👀 https://github.com/arrow-kt/arrow/pull/750 landed.

Sorry for the inconvenience!

cc @raulraja @pakoito @israelperezglez

**Comment by israelperezglez** [comment]
@Guardiola31337 No problem, thanks ;)

**Comment by raulraja** [comment]
@israelperezglez merge at will

**Comment by israelperezglez** [comment]
@raulraja Perfect, thanks ;)

**Pull request merged**
