### PR TITLE
Upgrade ktlint

### PR DESCRIPTION
**Pull request by rachelcarmena**
To support fun interfaces

### CODE REVIEW

**Comment by rachelcarmena** [comment]
I made the change just in `arrow-continuations` because the new version follows more code conventions that should be fixed in the arrow libraries.

**Comment by nomisRev** [comment]
😱 other projects are failing

**Comment by rachelcarmena** [comment]
> scream other projects are failing

Right because the new version follows more code conventions.

**Comment by rachelcarmena** [comment]
All checks have passed now after creating the PRs in the rest of repositories to disable rule `indent` :heavy_check_mark: 

Note: I cancelled the checks in the rest of repositories in order not to repeat the same executions. Merging!!

**Pull request merged**
