### PR TITLE
Provide test coverage for currying (#2894)

### PR DESCRIPTION
**Pull request by lgtout**
@nomisRev @raulraja 
I'd appreciate feedback on what I've done so far on tests for `currying`, e.g. naming, style, approach etc, so I can make any adjustments before moving on to the bulk of the work required.  
Thank you!

### CODE REVIEW

**Comment by serras** [comment]
I like the style! If possible, I would use a non-commutative operation instead of addition, since that property means that we cannot detect whether currying is passing arguments “the right way” or not.

**Comment by lgtout** [comment]
Ah, good idea!  Thanks.  So, string concatenation?

**Comment by serras** [comment]
> Ah, good idea! Thanks. So, string concatenation?

Or if you prefer to keep integers, you can use `x + 2 * y + 3 * z` or something similar.

**Comment by lgtout** [comment]
@serras @nomisRev Do you have a preference for integers vs strings or chars?

**Comment by serras** [comment]
Not really; I just mentioned integers so you didn't have to change too much of your current file contents.

**Pull request closed without merging**
