### PR TITLE
Fix StackOverflowError when combining sets.

### LINKED ISSUE #1717: SetK combineAll leads to StackOverflow
**Code example for the issue**
```kotlin
import arrow.core.SetK
import arrow.core.extensions.setk.monoid.monoid

fun main() {
    val result: Set<Int> = SetK.monoid<Int>().run {
        listOf(
            SetK.just(1),
            SetK.just(2)
        ).combineAll()
    }

    println(result)
}
```

**Expected result**
`SetK(set=[1, 2])`

**Actual result** 
```
Exception in thread "main" java.lang.StackOverflowError
	at arrow.core.extensions.SetKMonoid$DefaultImpls.plus(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.SetKSemigroup$DefaultImpls.combine(setk.kt:26)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.combine(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.typeclasses.Semigroup$DefaultImpls.plus(Semigroup.kt:15)
	at arrow.typeclasses.Monoid$DefaultImpls.plus(Monoid.kt)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.plus(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.plus(SetKMonoid.kt:16)
	at arrow.core.extensions.SetKSemigroup$DefaultImpls.combine(setk.kt:26)
	at arrow.core.extensions.SetKMonoid$DefaultImpls.combine(setk.kt)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.core.extensions.setk.monoid.SetKMonoidKt$monoid_singleton$1.combine(SetKMonoid.kt:16)
	at arrow.typeclasses.Semigroup$DefaultImpls.plus(Semigroup.kt:15)
	at arrow.typeclasses.Monoid$DefaultImpls.plus(Monoid.kt)
```

**Arrow version**: `0.10.0`

**Hint**
With ListK this is working just fine.

```kotlin
import arrow.core.ListK
import arrow.core.extensions.listk.monoid.monoid

fun main() {
    val result: List<Int> = ListK.monoid<Int>().run {
        listOf(
            ListK.just(1),
            ListK.just(2)
        ).combineAll()
    }

    println(result)
}
```

Results in `ListK(list=[1, 2])`

### PR DESCRIPTION
**Pull request by kitttn**
Closes #1717.

### CODE REVIEW

**Comment by calvellido** [comment]
#1719 solves the same issue :sweat_smile:

**Comment by kitttn** [comment]
Woops, i checked it out before, but it wasn't referenced in the issue, thought it's still free :D

**Comment by pakoito** [comment]
In the end @devesh-shetty was already working on a PR that added missing tests such as this one, and it caught the error even if he didn't know about these. It's merged already: https://github.com/arrow-kt/arrow/pull/1705, so should we close this now?

**Comment by kitttn** [comment]
Yes, we can close this, thanks!

**Pull request closed without merging**
