### PR TITLE
De-duplicate class names in `arrow-optics` and `arrow-optics-compose`

### LINKED ISSUE #3447: Duplicate class for arrow-optics-compose
Adding `arrow-optics-compose` like this:
```kotlin
dependency {
    implementation(platform("io.arrow-kt:arrow-stack:1.2.4"))
    implementation("io.arrow-kt:arrow-core")
    implementation("io.arrow-kt:arrow-optics")
    implementation("io.arrow-kt:arrow-optics-compose")
    ksp("io.arrow-kt:arrow-optics-ksp-plugin:1.2.4")
}
```

Causes this error when building:
```
Duplicate class arrow.optics.CopyKt found in modules arrow-optics-compose-jvm-1.2.4.jar -> arrow-optics-compose-jvm-1.2.4 (io.arrow-kt:arrow-optics-compose-jvm:1.2.4) and arrow-optics-jvm-1.2.4.jar -> arrow-optics-jvm-1.2.4 (io.arrow-kt:arrow-optics-jvm:1.2.4)

Go to the documentation to learn how to Fix dependency resolution errors.
```

Removing `arrow-core` and `arrow-optics` does not help.

### PR DESCRIPTION
**Pull request by serras**
Fixes #3447

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]
We released this in 1.2.x, no? I am okay with this small binary-break, since it's not a source breakage, and the module is brand new.

I don't expect anyone to have build a library on top, or someone relying on the Java class names directly.

**Comment by serras** [comment]
In fact, as #3447 shows, I think it's impossible to depend on `arrow-optics-compose` and `arrow-optics` at the same time, which seems like the most common case...

**Comment by err0r500** [comment]
Hi,
Do you have an idea when this PR will be released ? 👼
In the meantime, is there a workaround or should I use an alpha build?
Best,
Matthieu

**Comment by serras** [comment]
Unfortunately I cannot give you a precise date. The reasons are personal to the maintainers, but we hope to be able to come back fully in action soon. Thanks for your interest!

**Comment by wbervoets** [comment]
Any update on this issue? It makes arrow-optics-compose unusable

**Pull request merged**
