### PR TITLE
Redesign implementation

### LINKED ISSUE #1585: New design integration
We created this issue to integrate the new design in the real final arrow folder. After this we should test everything again:

- [x]  links

- [x] code snippets

- [x] error.html

- [x] `Blog and presentations` in the quickstar of core sidebar menu poining to the propper `Media section` site.

- [x] Change the navbar menu to point to the `Media section` site

### PR DESCRIPTION
**Pull request by AntonioMateoGomez**
This PR adds the new Arrow design to the web-site.

- [x] Review the CICD build

- [x] Use the `Arrow Playground` last version.

Closes #1585

### CODE REVIEW

**Comment by calvellido** [comment]
uuuuh

**Comment by raulraja** [comment]
giphy

**Comment by AntonioMateoGomez** [comment]
https://media.giphy.com/media/Z5eFxoKjf218c/giphy.gif

**Pull request merged**
