### PR TITLE
[WIP] Divide typeclasses

### PR DESCRIPTION
**Pull request by 1Jajen1**
Finally got around to doing something :)
Partially solves #284 (Only divide not apply, because apply is a lot of refractoring and has some annoyances when it comes to defaults for map etc.)

Docs are mostly wip atm.

Few things:
- There is no test for StateT because it explicitly requires a monad that is divisible and we don't have that afaik)
- There are no laws for decidable atm, there are some [here](http://hackage.haskell.org/package/contravariant-1.5/docs/src/Data.Functor.Contravariant.Divisible.html), but I don't really understand them well enough to attempt to port them :/ Scala cats and/or scalaz don't include them either afaik.
- Docs for Divisible are a bit annoying as tbh I don't quite see a good example usecase for conquer...
- Should the typeclass docs include an entry for each typeclass or would also work in one file as they share a lot of functionality (or better they share usecases)

### CODE REVIEW

**Comment by 1Jajen1** [comment]
Before I forget:

There are a few instances that would be really nice to have: Eq, Hash, Order.
But that does not work since they are a) not higherkind and b) even if they would be, since they inherit from each other not all of them can be.

Scala seems to not have that problem afaik (never used it but looking at it higher kinds can extend each other over there)

Haskell has a different problem (TypeClasses cannot be concrete types) and solves it by providing wrappers.
The wrapper solution to me sounds like the best one here, as one could easily add extension functions to convert back and forth (if needed, since the wrapper would delegate to the wrapped typeclass anyway).

Any ideas/thoughts?

**Comment by raulraja** [comment]
@1Jajen1 do you have an example of those instances that illustrates the problem?

**Comment by 1Jajen1** [comment]
The problem is not with instances, but more with higher kinded types and how they are emulated atm. (assuming thats what you meant :) )
If `Eq<A>` were to inherit from `EqOf<A>` then `Order<A>` which inherits from `Eq<A>` cannot be higher kinded on its own because it can't inherit from `OrderOf<A>` (`Kind<ForOrder, A>` can't extend `Kind<ForEq, A>` afaik).
So for these typeclasses to have instances they need to be higher kinded, which they cannot be if I understand it correctly.

**Comment by 1Jajen1** [comment]
I can write up an actual code example later (or maybe tomorrow) when I am back home.

**Comment by raulraja** [comment]
Monoid is higher kinded and it has an instance for `IO` as well as having one for `String` where `IO` is a type constructor and `String` is a monomorphic type, in case that is an indication that the issue you describe may be possible to encode.

**Comment by 1Jajen1** [comment]
Well yes, but monoid does not inherit from another higher kinded type does it? o.O
If now `Semigroup` would be changed to be higher kinded as well I don't think it'll work.

Making a typeclass higher kinded and writing instances for them worked fine, the only problem is that inheriting from a higher kinded type while being a higher kinded type as well does not work.

**Comment by 1Jajen1** [comment]
Code that hopefully outlines this properly.
```kotlin
class ForEq private constructor() { companion object }
typealias EqOf<A> = arrow.Kind<ForEq, A>
fun <A> EqOf<A>.fix(): Eq<A> = this as Eq<A>

interface Eq<A> : EqOf<A>

class ForOrder private constructor() { companion object }
typealias OrderOf<A> = arrow.Kind<ForOrder, A>
fun <A> OrderOf<A>.fix(): Order<A> = this as Order<A>

interface Order<A> : Eq<A>, OrderOf<A> // Type parameter F of Kind has inconsistent values: ForEq, ForOrder
```

**Comment by raulraja** [comment]
For what is worth we will send a KEEP for higher kinds after the one we sent for extensions.

**Comment by 1Jajen1** [comment]
Aren't those two in keep 87 atm? Or is that going to be split? 
Anyway, in the meantime should this be implemented by a wrapper type or just ignore it for now?

**Comment by raulraja** [comment]
They will be separated. I think ignore for now is probably best so we have less to port over later.

**Comment by 1Jajen1** [comment]
I'll close this for now. Will reopen a new pr for this tomorrow (I messed something up with git so I can't really salvage this :see_no_evil: )

**Pull request closed without merging**
