### PR TITLE
remove private val dummy from Left and Right

### PR DESCRIPTION
**Pull request by robstoll**
I removed the private property dummy from Left and Right, I do not really see why they would be required.

### CODE REVIEW

**Comment by pakoito** [comment]
>I do not really see why

I see you're fighting the compiler MUA HA HA HA 😈 

But seriously, if you arrive to a good solution we'll take it :D

**Comment by pakoito** [comment]
Detekt is our static analyzer. It's a nagger haha You have a couple of extra spaces on these lines:

	MultipleSpaces - [Left] at arrow-core/src/main/kotlin/arrow/core/Either.kt:154:35
	MultipleSpaces - [Right] at arrow-core/src/main/kotlin/arrow/core/Either.kt:167:35

**Comment by robstoll** [comment]
I am doing the change on the web. I figured I am not going to checkout the project just for such a small change (and fighting :dagger:  the compiler wouldn't be fun anymore :grin:).
Happy with the current solution (I'll clean up the spaces of course)?

**Comment by pakoito** [comment]
If it works, sure. It was a real problem with ambiguity inside and outside the package, so we use nulls everywhere. If it compilers & works let's go ahead with it.

**Comment by robstoll** [comment]
Well, the current solution wouldn't help with internal problems but the user shouldn't notice anything. I am not fussed if you do not merge the patch in the end. I understand that it would be painfull to add the generics everywhere.

**Comment by pakoito** [comment]
Yeah we don't want that, no. Too big of a burden. Some of the types are quite unreasonable, and the IDE hinting doesn't always collaborate.

**Comment by robstoll** [comment]
let us see how many errors we get. if there are only a few we could still consider to fix them and merge it, otherwise I close the pull request

**Comment by pakoito** [comment]
It's in the tests so it looks like it compiles 👍

**Comment by robstoll** [comment]
It's even green, surprise surprise, haha

**Comment by pakoito** [comment]
Well, cheers @robstoll 

Feel free to take a look at other instances of dummy around. They're easy to find :D

**Pull request merged**
