### PR TITLE
Upgrade KotlinTest to Kotest

### PR DESCRIPTION
**Pull request by nomisRev**
In preparation for moving test to common module for the MPP setup this PR upgrades KotlinTest to Kotest. (With the exception of the old Arrow Meta Kapt module)

This PR keeps everything as is as much as possible.
In almost all files only the following changes were applied:
 - forAll => checkAll
   - `==` => `shouldBe` as `forAll` expected `Boolean` but `checkAll` uses assertions
 - `Gen` => `Arb`

### CODE REVIEW

**Comment by franciscodr** [comment]
Task linked: [CU-j98mr4 [ 1.x.x ] Upgrade KotlinTest to Kotest](https://app.clickup.com/t/j98mr4)

**Review by rachelcarmena — APPROVED** [review]
AMAZING @nomisRev !! Just 2 small things:

- #2403 is ready to merge in case you want to check all the changes together
- Kotest version could be updated from 4.3.1 to 4.6.0

Congrats!!! :clap: :rocket:

**Comment by nomisRev** [comment]
@rachelcarmena bumped to 4.6.0.

Now some conflcits to fix 😅

**Review by raulraja — APPROVED** [review]
Thanks @nomisRev 🙏

**Pull request merged**
