### PR TITLE
unnecessary AQL dependency

### PR DESCRIPTION
**Pull request by i-walker**

### CODE REVIEW

**Comment by i-walker** [comment]
In the webpage they duplicated the imports. Was that intended?

**Comment by pakoito** [comment]
Oh, I mean that we want to list all the dependencies on the docs, optionals too. AQL is one of those.

And yes, we do manually sync the main README and the one in the docs, although the later has more things on it.

**Comment by i-walker** [comment]
I know, but I think you misunderstand me. Check this screenshot. 
There is one AQl import too much

Screenshot 2019-03-26 at 00 33 24

**Comment by pakoito** [comment]
Ooooooooooooooh. Yeah I see it now! Thanks :D

**Comment by i-walker** [comment]
Your welcome :)

**Pull request merged**
