### PR TITLE
Fixing the example

### PR DESCRIPTION
**Pull request by massimobertuzzi**
Fixing the docs for the Functor type class (see the example where multiplyBy2 is applied to two different datatypes)

### CODE REVIEW

**Comment by pakoito** [comment]
@JorgeCastilloPrz yes, ank only outputs the result of the last statement on a block.

**Comment by dcampogiani** [comment]
The goal was to remove the hardcoded

```kotlin
// Option(1)
```

And use ank to *print*

```kotlin
// Option(2)
```

But we never used ank, so if we have done something wrong any feedback is welcome

**Comment by pakoito** [comment]
@dcampogiani Cheers for your patience. If it passes CI I'll merge it immediately.

**Comment by pakoito** [comment]
@massimobertuzzi this PR has been neglected for far too long. I went ahead and fixed it straight into the repo, giving you credit for it. My sincere apologies for letting this PR rot for far too long.

https://github.com/arrow-kt/arrow/commit/c40f2af701067f1c710fa879594a290592076381

**Pull request closed without merging**
