### PR TITLE
Add video from .droidconSF 2018

### PR DESCRIPTION
**Pull request by Guardiola31337**
This PR adds _Manual documentation is dead. Long live automated documentation! Automated documentation with ΛNK_ [video](https://www.youtube.com/watch?v=CvNoX2gGd9c) to the docs.

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Where exactly? I was going to ask if there's was a concrete order, sorry!

**Comment by Guardiola31337** [comment]
> Where exactly?

> above `Building a DSL...in Kotlin`

:duck: Will update!

> This page is getting a facewash soon anyway.

Yeah, I agree! It needs some structure.

Thanks for the feedback @pakoito

**Comment by Guardiola31337** [comment]
@pakoito this is updated and ready for another round 👀

**Comment by pakoito** [comment]
Ready to party!

**Pull request merged**
