### PR TITLE
Update kotlinpoet to 1.5.0

### PR DESCRIPTION
**Pull request by hadilq**
This PR related to https://github.com/arrow-kt/arrow/issues/2032 and https://github.com/arrow-kt/arrow-core/pull/144.

### CODE REVIEW

**Comment by pakoito** [comment]
https://github.com/arrow-kt/arrow/pull/2154/checks?check_run_id=749182989#step:4:180

The build seems to fail

**Comment by hadilq** [comment]
@pakoito We need to merge https://github.com/arrow-kt/arrow-core/pull/144 first, then build would pass. Also after merging this PR we need to create another PR to revert https://github.com/arrow-kt/arrow-core/pull/144/commits/cb7cf33bf8c0e08aa17f525f565eac89692a6e37 commit.

**Comment by hadilq** [comment]
I created https://github.com/arrow-kt/arrow-core/pull/145 to revert back the `KOTLIN_POET_VERSION`

**Comment by rachelcarmena** [comment]
I think it's necessary to find another way to make this kind of changes. Thanks for your patience @hadilq !!

**Pull request merged**
