### PR TITLE
Move versions just related to arrow-core

### PR DESCRIPTION
**Pull request by hadilq**
It's related to https://github.com/arrow-kt/arrow-core/pull/153#discussion_r439352251
Of course, it'll be successfully built after merging https://github.com/arrow-kt/arrow-core/pull/153

### CODE REVIEW

**Comment by nomisRev** [comment]
The build is failing since we removed Kotlin-poet from the build which is used by kapt in the legacy Arrow-Meta project.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/runner/runners/2.263.0/work/arrow/arrow-core/arrow-meta/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':arrow-meta'.
> Could not get unknown property 'KOTLIN_POET_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**Comment by rachelcarmena** [comment]
Hi @nomisRev !! This PR is pending on https://github.com/arrow-kt/arrow-core/pull/153 which isn't on master branch. After merging https://github.com/arrow-kt/arrow-core/pull/153, this PR will be re-run.

**Comment by rachelcarmena** [comment]
The check errors that appear in this pull request now are also included in these issues that raised after merging https://github.com/arrow-kt/arrow-core/pull/153:

* https://github.com/arrow-kt/arrow-core/issues/166
* https://github.com/arrow-kt/arrow-core/issues/165

Both of them are related with `arrow-optics` library.

@hadilq in case you want to check these failures in advance, these Gradle tasks are available: https://github.com/arrow-kt/arrow/blob/master/docs/move-to-multi-repo/how-to-manage-several-repositories.md#gradle-tasks

**Comment by hadilq** [comment]
@rachelcarmena I'm checking them now! Thanks for the guide.

**Comment by rachelcarmena** [comment]
> @rachelcarmena I'm checking them now! Thanks for the guide.

Thanks to you @hadilq ! Please, let us know if we can help :raised_hands:

**Comment by hadilq** [comment]
I tried to fix it in https://github.com/arrow-kt/arrow-core/pull/168

**Comment by rachelcarmena** [comment]
> I tried to fix it in [arrow-kt/arrow-core#168](https://github.com/arrow-kt/arrow-core/pull/168)

Thank you so much @hadilq :raised_hands: Re-running!!

**Comment by hadilq** [comment]
Another one! https://github.com/arrow-kt/arrow-core/issues/170 Let me check it too.

**Comment by rachelcarmena** [comment]
> Another one! [arrow-kt/arrow-core#170](https://github.com/arrow-kt/arrow-core/issues/170) Let me check it too.

Of course, I think it's a flaky test in Arrow Fw library. @nomisRev is already working on it :raised_hands:

**Comment by rachelcarmena** [comment]
The build check error comes from a flaky test from Arrow Fw. Let's merge it! Thank you so much again @hadilq :raised_hands:

**Comment by hadilq** [comment]
@rachelcarmena Thank you for following up fast with the process, but https://github.com/arrow-kt/arrow-core/issues/170 is still open!

**Comment by rachelcarmena** [comment]
Thanks @hadilq, closed by @nomisRev :raised_hands:

**Comment by nomisRev** [comment]
Thanks for the awesome contributions @hadilq 👏

**Pull request merged**
