### PR TITLE
Introduce isLeft & isRight predicate API for Either

### PR DESCRIPTION
**Pull request by nomisRev**
In an interesting https://github.com/arrow-kt/arrow/pull/2913#discussion_r1097879312 between myself, @myuwono and @franciscodr in [Option API deprecation](https://github.com/arrow-kt/arrow/pull/2913) we came up with a set of new operators to replace `exists` in a new meaningful API that we thought was very Kotlin idiomatic.

This PR adds the relevant APIs for `Either`.

### CODE REVIEW

**Review by franciscodr — APPROVED** [review]
Thanks, @nomisRev!

**Review by i-walker — APPROVED** [review]
🙌🏾 Nice

**Comment by serras** [comment]
I really like this API design :)

**Review by myuwono — APPROVED** [review]
Thank you @nomisRev this is really awesome!

**Pull request merged**
