### PR TITLE
Concurrent defaults EmptyCoroutineContext 

### PR DESCRIPTION
**Pull request by nomisRev**

### CODE REVIEW

**Comment by nomisRev** [comment]
> You can't have parallelism with an empty coroutine context, by its pure definition :D

Wut!? 😫

**Comment by raulraja** [comment]
@pakoito that is true if the default is the EmptyCoroutineContext. What I'm proposing is that we have our own Default/IO dispatchers and make all concurrent ops default to the Default dispatcher based in the common pool so users can get the right behavior with defaults and optionally pass their own context if needed.

**Comment by pakoito** [comment]
@raulraja 'bout time we did :D Agreed.

**Comment by nomisRev** [comment]
Alright, shall I just close this then? @raulraja @pakoito

**Comment by JorgeCastilloPrz** [comment]
Do we have parallelization tests? Were those passing with this change?

**Comment by nomisRev** [comment]
@JorgeCastilloPrz We do have test for parallelization but none with the default value for ctx. They wouldn't pass I just tested locally.

**Comment by raulraja** [comment]
@nomisRev Yeah we need a couple of dispatchers one for CPU bound ops and other for IO blocking ops and have all our context dependent ops wherever makes sense default to the CPU common pool style one.

**Comment by nomisRev** [comment]
Closed and created ticket @ #1256

**Pull request closed without merging**
