### PR TITLE
Use `super` equals and hashCode overrides for NonEmptyList

### PR DESCRIPTION
**Pull request by RusticFlare**
Fixes https://github.com/arrow-kt/arrow/issues/2807 by removing the overrides of `equals` and `hashCode` in `NonEmptyList`, so that we use the implementations in `AbstractList`.

One thing to note is that Kotest's `shouldBe` doesn't use the `equals` function for `Iterable`, so I've tested the result of `==` explicitly (and left a comment to that effect).

(This is my first PR here 👋 so let me know if I've missed anything)

### CODE REVIEW

**Comment by nomisRev** [comment]
Hey @RusticFlare,

This change looks a bit dangerous to me, since it breaks `shouldBe` from Kotest. I know many people rely on `shouldBe` on Kotest.

I am wondering if the fix for that ticket is rather not simply removing `if (it::class != this::class)` from the `equals` implementation. That way it would solve the issue from the ticket, but wouldn't break `shouldBe` if not mistaken.

**Comment by nomisRev** [comment]
Or is `shouldBe` incorrect for this kind of comparisons 🤔

**Comment by RusticFlare** [comment]
Hi, it doesn't break `shouldBe`. I just couldn't use `shouldBe` to write a failing test because `shouldBe` doesn't use `equals` on `Iterable`. The current behaviour is an obvious bug and I don't think there is any value in overriding the `equals` and `hashCode` on `AbstractList`.

**Comment by nomisRev** [comment]
Okay, thanks for clarifying @RusticFlare! I miss-understood.

We cannot break the binary, so instead of removing I think we should manually delegate to the super class for now. We can break the binary in `2.x.x`. Then CI should turn green, it's now turning red on a binary breaking change.

> API check failed for project arrow-core.

**Comment by RusticFlare** [comment]
@nomisRev I've made the suggested change and hopefully the comment about `shouldBe` is clearer now

**Comment by RusticFlare** [comment]
Looks like CI is green 🎉 I can make another PR to remove the methods for `2.x.x` once this is merged.

**Review by nomisRev — APPROVED** [review]
Thank you for your first contribution @RusticFlare 🙏:clap::tada: Sorry for the hold-up.

**Review by i-walker — APPROVED** [review]

**Pull request merged**
