### PR TITLE
Upgrade Gradle to 7.1.1

### LINKED ISSUE #2442: Upgrade Gradle to 7.0
For us to support JDK 16 for the compilation of the project, we need to upgrade to Gradle 7 first, as I found out while adding multiple runs for different JDKs in #2392

### PR DESCRIPTION
**Pull request by pablisco**
Closes #2442 

This PR updates Gradle to the latest version, one so we can support JDK 16 and also to move the project forwards regarding Gradle features.

*   [x] Upgrade Gradle to 7.1.1
*   [x] Update dependencies notation to implementation and runtimeOnly (old compile and runtime are now deprecated)
*  [x] Upgrade Dokka to support Gradle 7
*  [x] Add support for JDK 16 compilation
*  [x] Fix JDK 16 build

### CODE REVIEW

**Comment by nomisRev** [comment]
@pablisco are we blocked waiting on a new version of Dokka?

**Comment by pablisco** [comment]
> @pablisco are we blocked waiting on a new version of Dokka?

I only had a quick look. I think the new version supports Grade 7. This is mainly to support JDK 16 so probably low priority

**Comment by pablisco** [comment]
I've updated Dokka to 1.5.0 and it compiles/builds however that's how far as I can tell if what I've changed works or not:

Me right now:



Any help to verify would be appreciated. cc: @raulraja @rachelcarmena (please tag anyone that may be able to validate this all works as it should 😅 )

**Comment by nomisRev** [comment]
@pablisco https://github.com/arrow-kt/arrow/blob/main/CONTRIBUTING.md#how-to-run-the-website-in-your-local-workspace

**Comment by pablisco** [comment]
Ok, SDK 16 is back on the menu. Also, the website seems to work ok. 
cc: @nomisRev

**Comment by nomisRev** [comment]
Awesome @pablisco!
Thanks for this, I'm going to double-check your branch also on the website update branch later today. If that looks good then I'm going to approve this PR 👍

I'm currently working on the docs and wanted to also bump Dokka. The Dokka team has done some really nice work reworking the Dokka eco-system, excited to be back up to date.

**Comment by nomisRev** [comment]
Awesome, bumped to Dokka 1.5.0 and nothing broke.
Thanks for this contrib @pablisco 🎉 🥳 👏 👏

**Review by nomisRev — APPROVED** [review]

**Review by raulraja — APPROVED** [review]
Thanks, @pablisco!

**Pull request merged**
