### PR TITLE
add merge to validated

### PR DESCRIPTION
**Pull request by agusotto96**
Adds a merge function to Validated, like the one found in Either

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]

**Comment by agusotto96** [comment]
Hi @nomisRev! Thanks a lot for answering, glad to help in any way, I'm really enjoying this library and all the resources provided by JetBrains and 47 Degrees.
By the way, I see that one of the checks failed, is this normal? Also, I have a few other small operators that I find interesting, should I keep adding them in PRs or should I open an issue?

**Comment by i-walker** [comment]
To keep consistency we may want to add this as an extension function like we did for Either https://github.com/arrow-kt/arrow/blob/c28e7da09ef07921efbc2419796c0edb45bb25ee/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L1383

**Review by nomisRev — CHANGES_REQUESTED** [review]
@i-walker, you're correct.
It needs to be placed outside of `Validated`. I didn't catch that on the diff with the indentation 😱 

This way it will not be conveniently accessible.

**Comment by nomisRev** [comment]
@agusotto96 I think CI failed with a false negative due to CI crashing.

> org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

**Comment by agusotto96** [comment]
Perfect, will check those out! I moved the function outside of Validated, hope its ok this time :sweat_smile:

**Review by agusotto96 — COMMENTED** [review]
Perfect, will check those out! I moved the function outside of Validated, hope its ok this time :sweat_smile:

**Review by i-walker — APPROVED** [review]
Thanks @agusotto96 👍🏾

**Review by nomisRev — APPROVED** [review]

**Comment by nomisRev** [comment]
Thank you for the contribution @agusotto96! And congrats on your first contribution to Arrow 🥳

**Comment by agusotto96** [comment]
Thanks! @i-walker @nomisRev

**Pull request merged**
