### PR TITLE
Add ensure, and ensureNotNull in computation DSL

### PR DESCRIPTION
**Pull request by nomisRev**
This PR adds some convenient syntax for mixing the `nullable` effect/monad with other effect/monads such as `either`, `option` and `nullable` itself.

It also deprecates the currently gotcha behavior of nullable `bind` syntax in `option { }`.
Example of gotcha behavior:

```kotlin
either<Int, String> {
  option<Int> {
     Either.Left(1).bind() // Expected to short-circuit but uses `fun <A> A?.bind(): A` instead and *doesnt* short-circuit,
     
  }.fold({ "0" }, Int::toString)
}
```

This was originally proposed in #2311.
The proposed `require`/`requireNotNull` syntax conflicts with with `kotlin.require` and `kotlin.requireNotNull` which is auto-imported and it can be easily confused. If it's mistake it leads to an exception instead of participating in the computation block.

### CODE REVIEW

**Comment by franciscodr** [comment]
Task linked: [CU-p9935d Add special validation syntax like kotlin.require and kotlin.requireNotNull](https://app.clickup.com/t/p9935d)

**Comment by nomisRev** [comment]
Closes https://github.com/arrow-kt/arrow/issues/2311

**Review by raulraja — APPROVED** [review]
Looks great @nomisRev !

**Review by i-walker — APPROVED** [review]
🙌🏾 Thanks Simon

**Pull request merged**
