### PR TITLE
IO Concurrency combinators

### PR DESCRIPTION
**Pull request by nomisRev**
This PR rewrite the old `IO<A>` concurrency operators to their new `IO<E, A>` equivalent.
Since this is the last set of combinators to be refactored I'm also fixing the tests in this PR.

 - [x] Rewrite Fork
 - [x] Rewrite ParMapN
 - [x] Rewrite RaceN
 - [x] Fix instances
 - [x] Arrow Fx compiles
 - [x] Arrow Fx Test compiles
 - [ ] Arrow Fx Tests pass

That would leave the runners, documentation and finalizing the final API for the subsequent PRs.

### CODE REVIEW

**Comment by nomisRev** [comment]
Whoops the changes are a bit messy but the build is green 😅
I'll fix the changes in the morning.

**Comment by pakoito** [comment]
+26,161 −11,437 


???

**Comment by nomisRev** [comment]
@pakoito I made a draft attempting to fix this in #1892

**Comment by nomisRev** [comment]
This PR has been closed in favor of #1892 which fixes the git history of the PR :)

**Comment by pakoito** [comment]
Delete branch?

**Pull request closed without merging**
