### PR TITLE
fix apidoc bad format

### LINKED ISSUE #1228: Formatting issue on data type generated docs
On data type docs the extension functions section is completely unreadable at the moment. [Example](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/index.html#extension-functions)

Can we do something to fix this @israelperezglez?

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Fix bad format due to markdown list on table style

Fixes #1228

### CODE REVIEW

**Comment by calvellido** [comment]
I don't think this fixes #1228 as a whole, does it?

**Comment by AdrianRaFo** [comment]
I tested locally it does

**Comment by calvellido** [comment]
I was under the assumption that #1228 was caused by a bad formatting generated by Dokka, @israelperezglez could you please clarify?

**Comment by AdrianRaFo** [comment]
that could make sense if all the file was a bad format but only one section has it. Also, I found really weird the return lists only in that section so after delete the `*` which gives the bad list format it was fixes

**Comment by JorgeCastilloPrz** [comment]
This is welcome but does not fix the issue. The issue is about wrongly rendered tables in the autogenerated sections of the doc. @israelperezglez was working on that.

**Pull request merged**
